export const ScreenNames = {
    SignIn: 'SignIn',
    SignUp: 'SignUp',
    //Client Screens
    ClientBook: 'ClientBook',
    ClientHomeAds: 'ClientHomeAds',
    ServiceDescr: 'ServiceDescr',
    ClientRequest: 'ClientRequest',
    ClientEvents: 'ClientEvents',
    FileFavorites: 'FileFavorites',
    Favorites: 'Favorites',
    ServiceDetail: 'ServiceDetail',
    SubDetailPrices: 'SubDetailPrices',
    Campaigns: 'Campaigns',
    ClientSearch: 'ClientSearch',
    PersonalInfo: 'PersonalInfo',
    UserProfile: 'UserProfile',
    CreateUser: 'CreateUser',
    Security: 'Security',
    Support: 'Support',
    Settings: 'Settings',
    ClientPayment: 'ClientPayment',
    ClientNotification: 'ClientNotification',
    LogOut: 'LogOut',
    ClientProfile: 'ClientProfile',
    

    // Provider Screens
    ProviderCreateListing: 'ProviderCreateListing',
    ProviderChooseService: 'ProviderChooseService',
    ProviderSetPhotos: 'ProviderSetPhotos',
    ProviderSetWorkingRegion: 'ProviderSetWorkingRegion',
    ProviderAddInfo: 'ProviderAddInfo',
    ProviderAddServiceDetail: 'ProviderAddServiceDetail',
    ProviderAddSubDetail: 'ProviderAddSubDetail',
    ProviderSetPrice: 'ProviderSetPrice',
    ProviderHomeAds: 'ProviderHomeAds',
    ProviderServiceShow: 'ProviderServiceShow',
    ProviderCalender: 'ProviderCalender',
    ProviderBookingRequest: 'ProviderBookingRequest',
    ProviderWaitingPay: 'ProviderWaitingPay',
    ProviderWaitingReply: 'ProviderWaitingReply',
    ProviderHome: 'ProviderHome',
    ProviderProfile: 'ProviderProfile',


    Splash: 'Splash',
    Results: 'Results',
    SearchServcies: 'SearchServcies',

};