import ForgotPassword from "../src/screens/ForgotPassword";

export const ScreenNames = {
    SignIn: 'SignIn',
    ForgotPassword: 'ForgotPassword',
    //Client Screens
    ClientBook: 'ClientBook',
    ClientHomeAds: 'ClientHomeAds',
    ServiceDescr: 'ServiceDescr',
    ClientRequest: 'ClientRequest',
    ClientEvents: 'ClientEvents',
    FileFavorites: 'FileFavorites',
    Favorites: 'Favorites',
    SubDetailPrices: 'SubDetailPrices',
    Campaigns: 'Campaigns',
    ClientSearch: 'ClientSearch',
    PersonalInfo: 'PersonalInfo',
    UserProfile: 'UserProfile',
    Security: 'Security',
    Support: 'Support',
    Settings: 'Settings',
    ClientPayment: 'ClientPayment',
    ClientNotification: 'ClientNotification',
    LogOut: 'LogOut',
    ClientProfile: 'ClientProfile',
    ReviewsScreen: 'ReviewsScreen',
    ClientSpecialDates: 'ClientSpecialDates',
    ClientRelations: 'ClientRelations',
    ClientShowRequest:'ClientShowRequest',
    ClientDuePayments: 'ClientDuePayments',
    ClientOldEvents:'ClientOldEvents',
    ClientIncomingRelation: 'ClientIncomingRelation',
    CreateInvetation: 'CreateInvetation',
    MyInvetationsCards: "MyInvetationsCards",
    InvetationShow:'InvetationShow',

    // Create User
    CreateUpersonalInfo: 'CreateUpersonalInfo',
    CreatePassword: 'CreatePassword',
    SetUserAddress: 'SetUserAddress',
    SetUserStatus: 'SetUserStatus',
    

    // Provider Screens
    ProviderCreateListing: 'ProviderCreateListing',
    ProviderChooseService: 'ProviderChooseService',
    ProviderSetPhotos: 'ProviderSetPhotos',
    ProviderSetWorkingRegion: 'ProviderSetWorkingRegion',
    ProviderAddInfo: 'ProviderAddInfo',
    ProviderAddServiceDetail: 'ProviderAddServiceDetail',
    ProviderAddSubDetail: 'ProviderAddSubDetail',
    ProviderSetPrice: 'ProviderSetPrice',
    ProviderHomeAds: 'ProviderHomeAds',
    ProviderServiceShow: 'ProviderServiceShow',
    ProviderCalender: 'ProviderCalender',
    ProviderBookingRequest: 'ProviderBookingRequest',
    ProviderWaitingPay: 'ProviderWaitingPay',
    ProviderWaitingReply: 'ProviderWaitingReply',
    ProviderHome: 'ProviderHome',
    ProviderCreateOffer: 'ProviderCreateOffer',
    ProviderProfile: 'ProviderProfile',
    ProviderSocialMediaScreen : 'ProviderSocialMedia',
    ProviderInitialWithDetailPrice : 'ProviderInitialWithDetailPrice',
    ProviderContantPrice: 'ProviderContantPrice',
    ProviderSetEventType: 'ProviderSetEventType',
    ProviderNotification: 'ProviderNotification',
    ProviderClientScreen: 'ProviderClientScreen',
    ProviderShowOffers: 'ProviderShowOffers',
    ProviderOfferDesc: 'ProviderOfferDesc',
    ProviderShowRequest: 'ProviderShowRequest',
    ProviderDuePayments: 'ProviderDuePayments',


    Splash: 'Splash',
    Results: 'Results',
    SearchServcies: 'SearchServcies',
    RequestDuePaymentsShow: 'RequestDuePaymentsShow',
    PaymentDetail: 'PaymentDetail',
    MakePayment: 'MakePayment'

};